version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-app-network

  backend:
    image: smitmark01/smittodobackend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - todo-app-network

  frontend:
    image: smitmark01/frontendtodo:latest
    ports:
      - "8501:8501"
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

volumes:
  mongo-data:
