version: '3'

services:
  backend:
    image: smitmark01/smittodobackend:latest
    ports:
      - "8080:8080"
    networks:
      - todo-app-network

  frontend:
    image: smitmark01/frontendtodo:latest
    ports:
      - "8501:8501"
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge


